#!/bin/sh

cd ~
repo="pagopa/developer-laptop"
curl --remote-name "https://raw.githubusercontent.com/$repo/master/mac"
curl --remote-name "https://raw.githubusercontent.com/$repo/master/Brewfile"
/usr/bin/env zsh mac 2>&1 | tee ~/laptop.log
